// Generated by support/web-diagrams/build.mjs. Fixed assets only.
pub(crate) fn asset(path: &str) -> Option<(&'static [u8], &'static str)> {
    match path {
        "/assets/vendor/diagrams/mermaid.js.LEGAL.txt" => Some((
            include_bytes!("../../../assets/web/vendor/diagrams/mermaid.js.LEGAL.txt"),
            "text/plain; charset=utf-8",
        )),
        "/assets/vendor/diagrams/mermaid-6181c00f4ae24586.js" => Some((
            include_bytes!("../../../assets/web/vendor/diagrams/mermaid-6181c00f4ae24586.js"),
            "text/javascript; charset=utf-8",
        )),
        "/assets/vendor/diagrams/markmap.js.LEGAL.txt" => Some((
            include_bytes!("../../../assets/web/vendor/diagrams/markmap.js.LEGAL.txt"),
            "text/plain; charset=utf-8",
        )),
        "/assets/vendor/diagrams/markmap-a4eb27b3741675d4.js" => Some((
            include_bytes!("../../../assets/web/vendor/diagrams/markmap-a4eb27b3741675d4.js"),
            "text/javascript; charset=utf-8",
        )),
        "/assets/vendor/diagrams/cached-svg.js.LEGAL.txt" => Some((
            include_bytes!("../../../assets/web/vendor/diagrams/cached-svg.js.LEGAL.txt"),
            "text/plain; charset=utf-8",
        )),
        "/assets/vendor/diagrams/cached-svg-ab3f10a46bdb33c3.js" => Some((
            include_bytes!("../../../assets/web/vendor/diagrams/cached-svg-ab3f10a46bdb33c3.js"),
            "text/javascript; charset=utf-8",
        )),
        "/assets/vendor/diagrams/LICENSES.txt" => Some((
            include_bytes!("../../../assets/web/vendor/diagrams/LICENSES.txt"),
            "text/plain; charset=utf-8",
        )),
        "/assets/vendor/diagrams/manifest.json" => Some((
            include_bytes!("../../../assets/web/vendor/diagrams/manifest.json"),
            "application/json; charset=utf-8",
        )),
        _ => None,
    }
}
