import { build } from 'esbuild';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
const here = path.dirname(fileURLToPath(import.meta.url)),
  repo = path.resolve(here, '../..');
const out = path.join(repo, 'packages/core/assets/web/vendor/diagrams');
fs.mkdirSync(out, { recursive: true });
const result = await build({
  absWorkingDir: here,
  entryPoints: { mermaid: 'src/mermaid.js', markmap: 'src/markmap.js', 'cached-svg': 'src/cached-svg.js' },
  outdir: out,
  bundle: true,
  platform: 'browser',
  format: 'iife',
  target: 'es2020',
  minify: true,
  legalComments: 'linked',
  metafile: true,
  write: false,
  loader: { '.woff': 'file', '.woff2': 'file', '.ttf': 'file', '.eot': 'file' },
  assetNames: '[name]-[hash]',
  logLevel: 'warning'
});
const packages = new Map();
for (const input of Object.keys(result.metafile.inputs)) {
  let dir = path.dirname(path.resolve(here, input));
  if (!dir.includes('node_modules')) continue;
  let meta;
  while (dir.startsWith(here)) {
    const file = path.join(dir, 'package.json');
    if (fs.existsSync(file)) {
      const candidate = JSON.parse(fs.readFileSync(file, 'utf8'));
      if (candidate.name) {
        meta = candidate;
        break;
      }
    }
    dir = path.dirname(dir);
  }
  if (!meta) throw Error('Missing package identity: ' + input);
  if (!packages.has(meta.name)) packages.set(meta.name, { dir, meta });
}
let license = '';
const deps = [];
for (const { dir, meta } of [...packages.values()].sort((a, b) => (a.meta.name < b.meta.name ? -1 : a.meta.name > b.meta.name ? 1 : 0))) {
  const files = fs
    .readdirSync(dir)
    .filter((f) => /^(licen[sc]e|copying|notice)([._-]|$)/i.test(f) && fs.statSync(path.join(dir, f)).isFile())
    .sort();
  if (!files.length) throw Error('Missing license for ' + meta.name);
  deps.push({
    name: meta.name,
    version: meta.version,
    license: meta.license || 'SEE LICENSE FILE',
    licenseFiles: files,
    repository: typeof meta.repository === 'string' ? meta.repository : meta.repository?.url,
    packageSource: 'https://registry.npmjs.org/' + meta.name + '/-/' + meta.name.split('/').at(-1) + '-' + meta.version + '.tgz'
  });
  license +=
    '\n===== ' + meta.name + ' ' + meta.version + ' =====\n' + files.map((f) => fs.readFileSync(path.join(dir, f), 'utf8')).join('\n');
}
const assets = result.outputFiles.map((file) => ({ name: path.basename(file.path), bytes: Buffer.from(file.contents) }));
const bundleUrls = {};
for (const asset of assets) {
  if (asset.name.endsWith('.js')) {
    const key = asset.name.slice(0, -3),
      digest = createHash('sha256').update(asset.bytes).digest('hex').slice(0, 16);
    asset.name = key + '-' + digest + '.js';
    bundleUrls[key] = '/assets/vendor/diagrams/' + asset.name;
  }
}
const previousFile = path.join(out, 'manifest.json');
if (fs.existsSync(previousFile)) {
  const previous = JSON.parse(fs.readFileSync(previousFile, 'utf8'));
  for (const old of previous.assets || [])
    if (/^[\w.-]+$/.test(old.file) && !assets.some((f) => f.name === old.file) && old.file !== 'LICENSES.txt')
      fs.rmSync(path.join(out, old.file), { force: true });
}
fs.writeFileSync(
  path.join(repo, 'packages/core/assets/web/diagram-config.js'),
  '// Generated by support/web-diagrams/build.mjs.\nwindow.LegnaDiagramAssets = ' + JSON.stringify(bundleUrls) + ';\n'
);
assets.push({ name: 'LICENSES.txt', bytes: Buffer.from(license) });
const hash = (bytes) => createHash('sha256').update(bytes).digest('hex');
for (const file of assets) {
  if (!/^[\w.-]+$/.test(file.name)) throw Error('Asset name');
  fs.writeFileSync(path.join(out, file.name), file.bytes);
}
const manifest = { dependencies: deps, assets: assets.map((f) => ({ file: f.name, bytes: f.bytes.length, sha256: hash(f.bytes) })) };
fs.writeFileSync(path.join(out, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n');
assets.push({ name: 'manifest.json' });
const mime = (name) =>
  name.endsWith('.js')
    ? 'text/javascript; charset=utf-8'
    : name.endsWith('.css')
      ? 'text/css; charset=utf-8'
      : name.endsWith('.json')
        ? 'application/json; charset=utf-8'
        : name.endsWith('.woff2')
          ? 'font/woff2'
          : name.endsWith('.woff')
            ? 'font/woff'
            : 'text/plain; charset=utf-8';
const rust =
  '// Generated by support/web-diagrams/build.mjs. Fixed assets only.\n' +
  "pub(crate) fn asset(path: &str) -> Option<(&'static [u8], &'static str)> {\n    match path {\n" +
  assets
    .map(
      (f) =>
        `        "/assets/vendor/diagrams/${f.name}" => Some((\n            include_bytes!("../../../assets/web/vendor/diagrams/${f.name}"),\n            "${mime(f.name)}",\n        )),`
    )
    .join('\n') +
  '\n        _ => None,\n    }\n}\n';
fs.writeFileSync(path.join(repo, 'packages/core/src/http/server/diagram_assets.rs'), rust);
console.log(JSON.stringify({ assets: assets.length, bytes: manifest.assets.reduce((a, f) => a + f.bytes, 0), packages: deps.length }));
