// Generates the offline web catalog from maintained app and web-only translations.
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '../..');
const catalog = {};
for (const locale of ['en', 'zh-CN', 'zh-TW', 'zh-HK']) {
  const app = JSON.parse(fs.readFileSync(path.join(root, 'app/assets/i18n', locale + '.json'), 'utf8'));
  function resolve(value) {
    if (typeof value !== 'string' || !value.startsWith('@:')) return value;
    return resolve(value.slice(2).split('.').reduce((node, key) => node[key], app));
  }
  catalog[locale] = { ...Object.fromEntries(Object.entries(app.web).filter(([key]) => !key.startsWith('@')).map(([key, value]) => [key, resolve(value)])),
    uploadRejected: resolve(app.sendPage.rejected), busy: resolve(app.sendPage.busy), dropHint: resolve(app.sendTab.placeItems),
    ...app.webPreview, textPreview: app.webTextPreview,
    webUi: JSON.parse(fs.readFileSync(path.join(root, 'packages/core/assets/web/i18n', locale + '.json'), 'utf8')) };
}
const output = '// Generated by support/scripts/generate_web_i18n.cjs.\nwindow.LegnaWebLocales = ' + JSON.stringify(catalog) + ';\n';
const target = path.join(root, 'packages/core/assets/web/web-i18n.js');
if (process.argv.includes('--check')) {
  if (fs.readFileSync(target, 'utf8') !== output) throw new Error('Web language bundle is stale');
} else fs.writeFileSync(target, output);
