// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:localsend_isolates/rust/api/cancel.dart';
import 'package:localsend_isolates/rust/api/model.dart';
import 'package:localsend_isolates/rust/api/stream.dart';
import 'package:localsend_isolates/rust/frb_generated.dart';

part 'http.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `resolve_file_content`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `from`, `from`, `from`, `from`

/// Creates an HTTP client.
/// Optional source address and exact interface name must be supplied together.
/// Supported desktop targets additionally constrain the interface. Android may
/// select a trusted live Network handle; no mode promises VPN policy bypass.
///
/// `expected_fingerprint` pins the peer to the certificate with that SHA-256
/// fingerprint (uppercase hex). It is enforced during the TLS handshake, so a
/// peer that does not present the expected certificate never receives the
/// request. Pass `None` only for discovery, where the peer is not known yet.
RsHttpClient createClient({
  required String privateKey,
  required String cert,
  required LsHttpClientVersion version,
  String? expectedFingerprint,
  int? timeoutMs,
  String? localAddress,
  String? interfaceName,
  String? androidNetworkHandle,
  String? androidNetworkEpoch,
}) => RustLib.instance.api.crateApiHttpCreateClient(
  privateKey: privateKey,
  cert: cert,
  version: version,
  expectedFingerprint: expectedFingerprint,
  timeoutMs: timeoutMs,
  localAddress: localAddress,
  interfaceName: interfaceName,
  androidNetworkHandle: androidNetworkHandle,
  androidNetworkEpoch: androidNetworkEpoch,
);

/// Synchronize trusted ConnectivityManager identities, never process-wide routing.
void configureAndroidNetworkRoutes({String? snapshot}) => RustLib.instance.api.crateApiHttpConfigureAndroidNetworkRoutes(snapshot: snapshot);

/// Private host-only source-end control storage. Never expose journal contents
/// or local paths through error messages or public integration APIs.
Future<String?> readSourceEndJournal({required String path}) => RustLib.instance.api.crateApiHttpReadSourceEndJournal(path: path);

Future<void> writeSourceEndJournal({required String path, required String data}) =>
    RustLib.instance.api.crateApiHttpWriteSourceEndJournal(path: path, data: data);

Future<void> prepareSourceEndJournal({required String path}) => RustLib.instance.api.crateApiHttpPrepareSourceEndJournal(path: path);

Future<RsSourceEndJournal> openSourceEndJournal({required String path}) => RustLib.instance.api.crateApiHttpOpenSourceEndJournal(path: path);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RsHttpClient>>
abstract class RsHttpClient implements RustOpaqueInterface {
  bool ackSourceEndGrant({required String ackId, required bool persisted});

  Future<void> cancel({required ProtocolType protocol, required String ip, required int port, required String sessionId});

  Future<RsSourceEndResult> endSource({
    required ProtocolType protocol,
    required String ip,
    required int port,
    String? publicKey,
    required RsSourceEndGrant grant,
    required String requestId,
    required RsCancellationToken cancelToken,
  });

  Future<PrepareUploadResult> prepareUpload({
    required ProtocolType protocol,
    required String ip,
    required int port,
    required PrepareUploadRequestDto payload,
    String? publicKey,
    String? pin,
    required RsCancellationToken cancelToken,
  });

  Future<ResultWithPublicKeyRegisterResponseDto> register({
    required ProtocolType protocol,
    required String ip,
    required int port,
    required RegisterDto payload,
  });

  /// Uploads a single file, emitting [RsUploadEvent]s on [sink].
  ///
  /// Failures are emitted as [RsUploadEvent::Failed] instead of being
  /// returned: flutter_rust_bridge discards the returned `Result` of
  /// functions taking a [StreamSink], so a returned error would become an
  /// uncaught async error killing the calling isolate.
  Stream<RsUploadEvent> upload({
    required ProtocolType protocol,
    required String ip,
    required int port,
    String? publicKey,
    required String sessionId,
    required String fileId,
    required String token,
    Dart2RustStreamReceiver? binary,
    String? path,
    int? fileDescriptor,
    required BigInt contentLength,
    String? resumeKey,
    bool? enableSourceEnd,
    required RsCancellationToken cancelToken,
  });
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RsSourceEndJournal>>
abstract class RsSourceEndJournal implements RustOpaqueInterface {
  Future<void> close();

  Future<String?> read();

  Future<void> write({required String data});
}

enum LsHttpClientVersion {
  v2,
  v3,
}

class PrepareUploadResult {
  final int statusCode;
  final PrepareUploadResponseDto? response;

  const PrepareUploadResult({
    required this.statusCode,
    this.response,
  });

  @override
  int get hashCode => statusCode.hashCode ^ response.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PrepareUploadResult && runtimeType == other.runtimeType && statusCode == other.statusCode && response == other.response;
}

class ResultWithPublicKeyRegisterResponseDto {
  final String? publicKey;
  final RegisterResponseDto body;

  const ResultWithPublicKeyRegisterResponseDto({
    this.publicKey,
    required this.body,
  });

  @override
  int get hashCode => publicKey.hashCode ^ body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResultWithPublicKeyRegisterResponseDto && runtimeType == other.runtimeType && publicKey == other.publicKey && body == other.body;
}

@freezed
sealed class RsHttpClientError with _$RsHttpClientError implements FrbException {
  const RsHttpClientError._();

  const factory RsHttpClientError.statusCode({
    required int status,
    String? message,
  }) = RsHttpClientError_StatusCode;
  const factory RsHttpClientError.resumeInterrupted({
    required bool retainedConfirmed,
  }) = RsHttpClientError_ResumeInterrupted;
  const factory RsHttpClientError.reqwest(
    String field0,
  ) = RsHttpClientError_Reqwest;
  const factory RsHttpClientError.json(
    String field0,
  ) = RsHttpClientError_Json;
  const factory RsHttpClientError.io(
    String field0,
  ) = RsHttpClientError_Io;
  const factory RsHttpClientError.other(
    String field0,
  ) = RsHttpClientError_Other;
  const factory RsHttpClientError.recovery({
    required RsRecoveryFailureKind kind,
    required RsRecoveryRetention retention,
    int? status,
  }) = RsHttpClientError_Recovery;
}

enum RsRecoveryFailureKind {
  retryable,
  authorizationRequired,
  sourceChanged,
  invalidResponse,
}

enum RsRecoveryRetention {
  notRetained,
  unknown,
  confirmed,
}

class RsSourceEndGrant {
  final int version;
  final String grantId;
  final String round;
  final String token;
  final BigInt expiresAtUnixMs;

  const RsSourceEndGrant({
    required this.version,
    required this.grantId,
    required this.round,
    required this.token,
    required this.expiresAtUnixMs,
  });

  @override
  int get hashCode => version.hashCode ^ grantId.hashCode ^ round.hashCode ^ token.hashCode ^ expiresAtUnixMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RsSourceEndGrant &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          grantId == other.grantId &&
          round == other.round &&
          token == other.token &&
          expiresAtUnixMs == other.expiresAtUnixMs;
}

enum RsSourceEndOutcome {
  cleared,
  publishedPreserved,
  active,
  publicationPending,
  retainedUnknown,
  unknownOrExpired,
  superseded,
  authorizationRequired,
}

class RsSourceEndResult {
  final RsSourceEndOutcome outcome;
  final String? receiptId;
  final int removedFiles;
  final BigInt unlinkedBytes;

  const RsSourceEndResult({
    required this.outcome,
    this.receiptId,
    required this.removedFiles,
    required this.unlinkedBytes,
  });

  @override
  int get hashCode => outcome.hashCode ^ receiptId.hashCode ^ removedFiles.hashCode ^ unlinkedBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RsSourceEndResult &&
          runtimeType == other.runtimeType &&
          outcome == other.outcome &&
          receiptId == other.receiptId &&
          removedFiles == other.removedFiles &&
          unlinkedBytes == other.unlinkedBytes;
}

@freezed
sealed class RsUploadEvent with _$RsUploadEvent {
  const RsUploadEvent._();

  const factory RsUploadEvent.sourceEndGrant({
    required String ackId,
    required RsSourceEndGrant grant,
  }) = RsUploadEvent_SourceEndGrant;
  const factory RsUploadEvent.sourceEndUnavailable() = RsUploadEvent_SourceEndUnavailable;

  /// The upload progress as a fraction (0.0 to 1.0). Throttled.
  const factory RsUploadEvent.progress({
    required double progress,
  }) = RsUploadEvent_Progress;

  /// Source/cache validation only; never transfer throughput.
  const factory RsUploadEvent.verification({
    required BigInt verifiedBytes,
    required BigInt totalBytes,
  }) = RsUploadEvent_Verification;

  /// The upload failed. Always the last event of the stream.
  const factory RsUploadEvent.failed({
    required RsHttpClientError error,
  }) = RsUploadEvent_Failed;

  /// A real bounded retry delay, not transfer or verification progress.
  const factory RsUploadEvent.recovery({
    required bool waiting,
    required int attempt,
    required int retryAfterMs,
  }) = RsUploadEvent_Recovery;
}
