// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:localsend_isolates/rust/frb_generated.dart';

Future<RsApiKeyDraft> createIntegrationApiKey({required String name, required String grant, BigInt? expiresAt}) =>
    RustLib.instance.api.crateApiIntegrationCreateIntegrationApiKey(name: name, grant: grant, expiresAt: expiresAt);

/// Validate before writing local preferences, including when receiving is off.
Future<void> validateIntegrationApiConfiguration({required String config}) =>
    RustLib.instance.api.crateApiIntegrationValidateIntegrationApiConfiguration(config: config);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RsApiKeyDraft>>
abstract class RsApiKeyDraft implements RustOpaqueInterface {
  /// Verifier-bearing persistence record. Keep out of public state and diagnostics.
  Future<String> record();

  /// Consume after persistence succeeds. Later calls never recover the plaintext.
  Future<String?> takeSecret();
}
