// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:localsend_isolates/rust/frb_generated.dart';

Future<List<RsNetworkAddress>> getNetworkAddresses({List<String>? whitelist, List<String>? blacklist}) =>
    RustLib.instance.api.crateApiNetworkGetNetworkAddresses(whitelist: whitelist, blacklist: blacklist);

/// One usable local address with its original OS interface and real prefix.
class RsNetworkAddress {
  final String name;
  final int? index;
  final String address;
  final int? prefixLength;
  final bool isIpv6;

  const RsNetworkAddress({
    required this.name,
    this.index,
    required this.address,
    this.prefixLength,
    required this.isIpv6,
  });

  @override
  int get hashCode => name.hashCode ^ index.hashCode ^ address.hashCode ^ prefixLength.hashCode ^ isIpv6.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RsNetworkAddress &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          index == other.index &&
          address == other.address &&
          prefixLength == other.prefixLength &&
          isIpv6 == other.isIpv6;
}
