// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:localsend_isolates/rust/frb_generated.dart';

/// Set the private application-support registry before native receiving starts.
/// This does not scan or delete files in any destination.
Future<void> configureReceiveCacheRegistry({required String directory}) =>
    RustLib.instance.api.crateApiReceiveCacheConfigureReceiveCacheRegistry(directory: directory);

/// Bounded worker cleanup of registered, unlocked non-resumable attempts.
/// Returns aggregate counts/reasons, never native paths or access credentials.
Future<String> cleanupReceiveCacheRegistry({required int limit}) =>
    RustLib.instance.api.crateApiReceiveCacheCleanupReceiveCacheRegistry(limit: limit);

/// Bounded, read-only inventory of registered caches and cleanup eligibility.
/// Returns opaque record IDs and display names, never paths or credentials.
Future<String> inspectReceiveCacheRegistry({required int limit}) =>
    RustLib.instance.api.crateApiReceiveCacheInspectReceiveCacheRegistry(limit: limit);

/// Configure local native-receive crash-residue retention. Modes: immediate,
/// hour (the default, exactly 3600 seconds), days (1..3650), manual;
/// days must be absent for the other modes. The app
/// persists this preference. Invalid input leaves the current policy unchanged.
/// Returns {"mode":"immediate"|"hour"|"days"|"manual","days":null|number}.
Future<String> configureReceiveCacheRetentionPolicy({required String mode, int? days}) =>
    RustLib.instance.api.crateApiReceiveCacheConfigureReceiveCacheRetentionPolicy(mode: mode, days: days);

/// Explicit user cleanup, ignoring age only. Active/identity protections remain.
Future<String> cleanupReceiveCacheRegistryNow({required int limit}) =>
    RustLib.instance.api.crateApiReceiveCacheCleanupReceiveCacheRegistryNow(limit: limit);

/// Read-only preview for explicit cleanup-now; ignores age, not safety checks.
Future<String> inspectReceiveCacheRegistryNow({required int limit}) =>
    RustLib.instance.api.crateApiReceiveCacheInspectReceiveCacheRegistryNow(limit: limit);

/// Return the effective local preference, not a persisted application setting.
Future<String> getReceiveCacheRetentionPolicy() => RustLib.instance.api.crateApiReceiveCacheGetReceiveCacheRetentionPolicy();

/// Runs under a native-approved coordinated directory lease held by the caller.
/// Only registered non-resumable residues inside this root are considered;
/// activity locks, identity proofs and retention remain mandatory.
Future<String> maintainReceiveCacheRegistryInScope({required String directory, required int limit, required bool inspection, required bool force}) =>
    RustLib.instance.api.crateApiReceiveCacheMaintainReceiveCacheRegistryInScope(
      directory: directory,
      limit: limit,
      inspection: inspection,
      force: force,
    );
