// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:localsend_isolates/rust/api/model.dart';
import 'package:localsend_isolates/rust/frb_generated.dart';

part 'server.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `abort_download_decision`, `adopt_write_descriptor`, `answer_publication`, `deliver_directory_document`, `deliver_directory_write`, `deliver_source_end_scope`, `directory_document_result`, `directory_write_header`, `directory_write_result`, `emit_expired_download_decisions`, `handle_server_event`, `handle_web_event`, `parse_cache_recovery`, `prune_source_end_scopes`, `recv_opt`, `register_download_decision`, `register_publication`, `register_source_end_scope`, `resolve_cached_files`, `resolve_file_content`, `resolve_upload_target`, `stop`, `take_android_descriptor`, `take_expired_download_decisions`, `take_prepare_decision`, `take_upload_target`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DirectoryWriteState`, `PendingDirectoryDocument`, `PendingDirectoryWrite`, `PendingSourceEndScope`, `PendingUploadTarget`, `ServerInstance`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Delete one registered private export through pinned no-follow directory handles.
/// The host must hold the export store's process lease and exclude active stages.
Future<String> cleanupWorkspaceCapture({required String root, required String id}) =>
    RustLib.instance.api.crateApiServerCleanupWorkspaceCapture(root: root, id: id);

/// Consume a temporary SAF descriptor pair and close both before returning.
/// An unsupported filesystem is a negative capability, not a no-lock success.
Future<bool> probeReceiveDescriptorPair({required int cacheDescriptor, required int stagingDescriptor}) =>
    RustLib.instance.api.crateApiServerProbeReceiveDescriptorPair(cacheDescriptor: cacheDescriptor, stagingDescriptor: stagingDescriptor);

/// Takes ownership before validating the supplied proof. Rejection closes the FD.
Future<RsReceiveCleanupGuard> acquireReceiveCleanupGuard({required int descriptor, required BigInt expectedLength, required String expectedSha256}) =>
    RustLib.instance.api.crateApiServerAcquireReceiveCleanupGuard(
      descriptor: descriptor,
      expectedLength: expectedLength,
      expectedSha256: expectedSha256,
    );

/// Adopt the independently opened read-only descriptor before checking proof
/// fields. Rejected or abandoned bridge calls retain no detached file handle.
Future<RsReceivePublicationGuard> acquireReceivePublicationGuard({required int fileDescriptor, required BigInt length, required String sha256}) =>
    RustLib.instance.api.crateApiServerAcquireReceivePublicationGuard(fileDescriptor: fileDescriptor, length: length, sha256: sha256);

/// Starts the HTTP server on the given port (IPv4 and IPv6).
/// The server runs until [RsHttpServer::stop] is called.
///
/// [web] configures the pages served to browsers: [WebParams::mode] selects
/// the download page ([WebMode::Download], so web browsers can download the
/// offered files), the upload page ([WebMode::Upload]) or no web share at all
/// ([WebMode::Disabled], serving the 403 page).
///
/// Passing [show_token] enables the internal `show` endpoint that lets another
/// application instance request this one to show itself (emitted as
/// [RsServerEvent::Show]). The token guards the endpoint against other clients.
///
/// Events are received by listening to [RsHttpServer::listen].
Future<RsHttpServer> startServer({
  required int port,
  TlsConfig? tls,
  required String alias,
  required String version,
  String? deviceModel,
  DeviceType? deviceType,
  required String fingerprint,
  String? pin,
  required bool verifyChecksums,
  required WebParams web,
  String? showToken,
}) => RustLib.instance.api.crateApiServerStartServer(
  port: port,
  tls: tls,
  alias: alias,
  version: version,
  deviceModel: deviceModel,
  deviceType: deviceType,
  fingerprint: fingerprint,
  pin: pin,
  verifyChecksums: verifyChecksums,
  web: web,
  showToken: showToken,
);

/// Releases a source acquired after the owning server has already stopped.
Future<void> discardDownloadSource({String? path, int? fileDescriptor}) =>
    RustLib.instance.api.crateApiServerDiscardDownloadSource(path: path, fileDescriptor: fileDescriptor);

/// Derive a persistent workspace verifier without blocking Flutter's UI isolate.
/// The result is private configuration, never a browser-visible password.
Future<String> hashDirectoryPassword({required String password}) => RustLib.instance.api.crateApiServerHashDirectoryPassword(password: password);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RsHttpServer>>
abstract class RsHttpServer implements RustOpaqueInterface {
  /// Cancels the active upload session, e.g. because the user aborted the
  /// transfer on the receiving side.
  ///
  /// Uploads that are already in progress still run to completion, but new
  /// upload requests fail and a new session can be created.
  /// No [RsServerEvent::SessionEnd] is emitted: the application initiated
  /// the cancellation itself.
  Future<void> cancelSession({required String sessionId});

  Future<bool> cancelWebDownload({required String id});

  /// Trusted host only: the destination is an owned staging root, never API input.
  Future<String> captureWorkspaceSources({
    required String workspaceId,
    required BigInt generation,
    required String files,
    required String destination,
  });

  /// Atomically authorizes a queued management action before the host mutates persistence.
  Future<bool> claimWorkspaceManagement({required String requestId});

  /// Atomically replace named directory routes without restarting the listener.
  Future<String> configureDirectoryWorkspaces({required String config});

  /// Apply integration policy without restarting any transfer listener.
  Future<String> configureIntegrationApi({required String config});

  /// Fails this request only; other requests for the same session/file survive.
  Future<void> failFileDownload({required String requestId, required String sessionId, required String fileId});

  /// Fails the pending [RsServerEvent::FileUpload] event, e.g. because
  /// the application failed to prepare a save target for the file.
  ///
  /// The upload request fails with an error response and the file is marked
  /// as failed. Does nothing if the upload was already answered.
  Future<void> failFileUpload({required String sessionId, required String fileId, String? expectedAttemptId});

  /// Real loopback API execution. A supplied Android read descriptor transfers once,
  /// before parsing or any asynchronous work; all rejection paths retain RAII ownership.
  Future<String> integrationApiRequest({required String request, int? fileDescriptor});

  /// Local management reads only redacted metadata, never verifiers or secrets.
  Future<String> integrationApiSnapshot();

  /// Emits server events until the server is stopped.
  /// Can only be listened to once.
  ///
  /// The v2 protocol, the web download (download API), and the internal endpoint
  /// events are all emitted on the same stream.
  ///
  /// Also returns when the Dart side of the stream is gone (e.g. after a
  /// hot restart), so this call does not keep the server alive forever.
  Stream<RsServerEvent> listen();

  /// Private lookup under a fresh approved session and exact active attempt.
  /// The peer never supplies an old path, token or receipt identity here.
  Future<RsReceiveRecoveryTarget> lookupReceiveRecoveryTarget({
    required String sessionId,
    required String fileId,
    required String expectedAttemptId,
    required String approvedDirectory,
    required String requestedName,
  });

  /// Revoke selected file IDs and publish replacements without restarting listeners.
  Future<void> patchWebWorkspace({required Map<String, FileDto> files, required List<String> removeFileIds});

  /// The actual bound HTTP port, which may differ after a conflict fallback.
  Future<int> port();

  /// Internal cached-descriptor foundation. Both files must be new, empty, seekable
  /// owned documents. Paths are existing-file test/desktop inputs; no creation or
  /// truncation happens here. Android must transfer each fresh detached FD once.
  /// This API does not activate the provider adapter in the normal receive path.
  Stream<double> respondCachedFileUpload({
    required String sessionId,
    required String fileId,
    required String transactionId,
    String? cachePath,
    int? cacheDescriptor,
    String? stagingPath,
    int? stagingDescriptor,
    required BigInt fileSize,
  });

  /// Reply only after the app-owned observation state has been durably written.
  Future<void> respondDirectoryContent({required String requestId, String? response});

  /// Native ownership transfers once at entry, including late/rejected replies.
  Future<bool> respondDirectoryDocument({required String requestId, String? payload, int? fileDescriptor, String? error});

  /// Private descriptor-pair ownership transfer; accepts real late publication
  /// outcomes on the original handle even after its listening socket stopped.
  Future<bool> respondDirectoryDocumentWrite({
    required String requestId,
    String? payload,
    int? cacheDescriptor,
    int? stagingDescriptor,
    String? error,
  });

  /// False means the peer has cancelled, expired, or this decision was already used.
  Future<bool> respondDirectoryUploadApproval({required String requestId, required bool accept});

  /// Answers the pending [RsServerEvent::WebFileDownload] event with the source
  /// the file content should be read from (either a path or a file descriptor).
  ///
  /// The server reads the content and streams it to the web client.
  Future<bool> respondFileDownload({required String requestId, required String sessionId, required String fileId, String? path, int? fileDescriptor});

  /// Answers the pending [RsServerEvent::FileUpload] event with the target
  /// the file should be saved to (either a path or a file descriptor)
  /// and waits until the file has been received completely.
  ///
  /// The progress (fraction of [file_size]) is emitted on [sink]
  /// while the file is being received. Failures are emitted on [sink] as
  /// well: flutter_rust_bridge discards the returned `Result` of functions
  /// taking a [StreamSink], so a returned error would become an uncaught
  /// async error killing the calling isolate.
  ///
  /// Timestamps provided in the sender's file metadata are applied to the
  /// written file by the server.
  Stream<double> respondFileUpload({
    required String sessionId,
    required String fileId,
    String? path,
    int? fileDescriptor,
    required BigInt fileSize,
    String? expectedAttemptId,
  });

  /// Answers the pending [RsServerEvent::WebPrepareDownload] event.
  ///
  /// Passing `true` accepts the download request, `false` declines it.
  Future<void> respondPrepareDownload({required String sessionId, required bool accept});

  /// Answers the pending [RsServerEvent::PrepareUpload] event.
  ///
  /// Passing the accepted file IDs (a subset of the offered files) accepts the request.
  /// Passing `None` declines the request.
  Future<bool> respondPrepareUpload({
    required String sessionId,
    List<String>? acceptedFileIds,
    List<String>? resumableFileIds,
    List<String>? durableFileIds,
  });

  /// A journal acknowledgement cannot consume a publication acknowledgement.
  Future<bool> respondReceiveCacheIdentity({
    required String sessionId,
    required String fileId,
    required String attemptId,
    required String transactionId,
    String? error,
    String? recoveryTransactionId,
    String? recoveryIdentityJson,
    int? recoverySourceDescriptor,
  });

  Future<bool> respondReceiveCacheRecovered({
    required String sessionId,
    required String fileId,
    required String attemptId,
    required String transactionId,
    String? error,
  });

  /// Granted replies finish only when the actual core source-end worker drains.
  Future<bool> respondReceiveSourceEndScope({required String requestId, required bool granted});

  /// Match every identity before consuming a responder. A stale or duplicate
  /// reply can never approve the next whole-file retry.
  Future<bool> respondUploadPublication({
    required String sessionId,
    required String fileId,
    required String attemptId,
    required String transactionId,
    String? error,
  });

  /// Complete an already claimed action with a bounded, root-free receipt.
  Future<void> respondWorkspaceManagement({required String requestId, required String response});

  /// Enable or close only the temporary share on the existing listener.
  Future<void> setWebWorkspace({required bool enabled, required Map<String, FileDto> files, String? pin, required bool allowUpload});

  /// Stops the server.
  /// Returns after the listeners are closed, so the port can be bound again.
  Future<void> stop();

  /// Filesystem capability probe only; never creates or selects a user file.
  Future<bool> supportsReceiveRecoveryTarget({required String approvedDirectory, required String requestedName});

  /// Append immutable shared IDs and change permission without restarting listeners.
  Future<void> updateWebWorkspace({required Map<String, FileDto> files, required bool allowUpload});

  Future<String> webDownloadActivity();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RsReceiveCleanupGuard>>
abstract class RsReceiveCleanupGuard implements RustOpaqueInterface {
  Future<void> release();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RsReceivePublicationGuard>>
abstract class RsReceivePublicationGuard implements RustOpaqueInterface {
  Future<void> release();
}

class RegisterDtoV2 {
  final String alias;
  final String version;
  final String? deviceModel;
  final DeviceType? deviceType;
  final String fingerprint;
  final int port;
  final ProtocolType protocol;
  final bool download;

  const RegisterDtoV2({
    required this.alias,
    required this.version,
    this.deviceModel,
    this.deviceType,
    required this.fingerprint,
    required this.port,
    required this.protocol,
    required this.download,
  });

  @override
  int get hashCode =>
      alias.hashCode ^
      version.hashCode ^
      deviceModel.hashCode ^
      deviceType.hashCode ^
      fingerprint.hashCode ^
      port.hashCode ^
      protocol.hashCode ^
      download.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RegisterDtoV2 &&
          runtimeType == other.runtimeType &&
          alias == other.alias &&
          version == other.version &&
          deviceModel == other.deviceModel &&
          deviceType == other.deviceType &&
          fingerprint == other.fingerprint &&
          port == other.port &&
          protocol == other.protocol &&
          download == other.download;
}

/// Owned durable-receive registry identity. A path is only a candidate until
/// the normal save result confirms full content verification/publication.
class RsReceiveRecoveryTarget {
  final String? path;
  final String receiptId;
  final BigInt? completedUnixMs;

  const RsReceiveRecoveryTarget({
    this.path,
    required this.receiptId,
    this.completedUnixMs,
  });

  @override
  int get hashCode => path.hashCode ^ receiptId.hashCode ^ completedUnixMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RsReceiveRecoveryTarget &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          receiptId == other.receiptId &&
          completedUnixMs == other.completedUnixMs;
}

@freezed
sealed class RsServerEvent with _$RsServerEvent {
  const RsServerEvent._();

  /// A private coordinated root lease for source-end cleanup, not peer approval.
  const factory RsServerEvent.receiveSourceEndScope({
    required String requestId,
    required String directory,
  }) = RsServerEvent_ReceiveSourceEndScope;

  /// Private observation persistence request; never expose its source locator.
  const factory RsServerEvent.directoryContent({
    required String requestId,
    required String request,
  }) = RsServerEvent_DirectoryContent;

  /// Bounded snapshot of actual temporary-share HTTP response bodies.
  const factory RsServerEvent.webDownloadActivity({
    required String snapshot,
  }) = RsServerEvent_WebDownloadActivity;
  const factory RsServerEvent.directoryDocument({
    required String requestId,
    required String request,
  }) = RsServerEvent_DirectoryDocument;
  const factory RsServerEvent.directoryDocumentCancelled({
    required String requestId,
  }) = RsServerEvent_DirectoryDocumentCancelled;
  const factory RsServerEvent.directoryDocumentWrite({
    required String requestId,
    required String request,
  }) = RsServerEvent_DirectoryDocumentWrite;
  const factory RsServerEvent.directoryDocumentWriteCancelled({
    required String requestId,
  }) = RsServerEvent_DirectoryDocumentWriteCancelled;

  /// Only already-admitted write owners may finish after listener stop.
  const factory RsServerEvent.directoryDocumentWriteDraining() = RsServerEvent_DirectoryDocumentWriteDraining;
  const factory RsServerEvent.directoryUploadApproval({
    required String requestId,
    required String request,
  }) = RsServerEvent_DirectoryUploadApproval;
  const factory RsServerEvent.directoryUploadApprovalAborted({
    required String requestId,
  }) = RsServerEvent_DirectoryUploadApprovalAborted;

  /// An explicitly authorized integration request for the persistent workspace catalog.
  const factory RsServerEvent.workspaceManagement({
    required String requestId,
    required String request,
  }) = RsServerEvent_WorkspaceManagement;

  /// A device registered itself via `POST /api/localsend/v2/register`.
  ///
  /// On TLS, this event is only emitted when `info.fingerprint` matches the
  /// fingerprint of the client certificate verified during the mTLS
  /// handshake, so the fingerprint cannot be spoofed.
  const factory RsServerEvent.register({
    required String ip,
    required RegisterDtoV2 info,
  }) = RsServerEvent_Register;

  /// A sender requests to upload files via `POST /api/localsend/v2/prepare-upload`.
  const factory RsServerEvent.prepareUpload({
    /// The session ID the upload session will have when the request is accepted.
    required String sessionId,
    required String ip,
    required RegisterDtoV2 info,

    /// The SHA-256 fingerprint (uppercase hex) of the sender's client
    /// certificate verified during the mTLS handshake. Unlike
    /// `info.fingerprint`, this value cannot be spoofed.
    /// `None` when the server runs without TLS.
    String? certFingerprint,
    required Map<String, FileDto> files,
  }) = RsServerEvent_PrepareUpload;

  /// An accepted file is being uploaded via `POST /api/localsend/v2/upload`.
  const factory RsServerEvent.fileUpload({
    required String sessionId,
    required String fileId,
    required FileDto file,

    /// Internal-only approved durable attempt; missing retains original behavior.
    bool? durableRecovery,
    String? recoveryAttemptId,
  }) = RsServerEvent_FileUpload;

  /// Verification bytes are not transferred bytes or a resumable offset.
  const factory RsServerEvent.fileVerification({
    required String sessionId,
    required String fileId,
    required String attemptId,
    required BigInt verifiedBytes,
    required BigInt totalBytes,
    required bool verifying,
  }) = RsServerEvent_FileVerification;

  /// The provider must durably bind the exact cache identity before body writes.
  const factory RsServerEvent.receiveCacheIdentity({
    required String sessionId,
    required String fileId,
    required String attemptId,
    required String transactionId,
    required String identityJson,
  }) = RsServerEvent_ReceiveCacheIdentity;
  const factory RsServerEvent.receiveCacheRecovered({
    required String sessionId,
    required String fileId,
    required String attemptId,
    required String transactionId,
    required String sourceTransactionId,
    required BigInt sourceLength,
    required String sourceSha256,
  }) = RsServerEvent_ReceiveCacheRecovered;

  /// Verified cache export is ready; publication must be acknowledged before HTTP success.
  const factory RsServerEvent.publishUpload({
    required String sessionId,
    required String fileId,
    required String attemptId,
    required String transactionId,
    required BigInt size,
    required String sha256,
  }) = RsServerEvent_PublishUpload;

  /// All handles for this attempt are closed. This does not authorize guessing document URIs.
  const factory RsServerEvent.uploadCacheReleased({
    required String sessionId,
    required String fileId,
    required String attemptId,
    required String transactionId,
    required bool published,
  }) = RsServerEvent_UploadCacheReleased;

  /// An upload session ended.
  const factory RsServerEvent.sessionEnd({
    required String sessionId,
    required SessionEndReasonV2 reason,
  }) = RsServerEvent_SessionEnd;

  /// A prepare-upload request was aborted before a session was created,
  /// e.g. the sender disconnected while the application was still deciding.
  /// The [RsServerEvent::PrepareUpload] with the same session ID
  /// no longer needs to be answered.
  const factory RsServerEvent.prepareUploadAborted({
    required String sessionId,
  }) = RsServerEvent_PrepareUploadAborted;

  /// `POST /api/localsend/v2/cancel` was received for a session this server
  /// does not manage: the remote device cancels a transfer this application
  /// is currently *sending* to it. The application must verify that [ip]
  /// matches the target of the send session before cancelling it.
  const factory RsServerEvent.cancelReceived({
    required String ip,
    required String sessionId,
  }) = RsServerEvent_CancelReceived;

  /// A web client requests to download the shared files via `POST /api/localsend/v2/prepare-download`.
  ///
  /// Must be answered with [RsHttpServer::respond_prepare_download].
  const factory RsServerEvent.webPrepareDownload({
    required String ip,
    required String sessionId,
    String? userAgent,
  }) = RsServerEvent_WebPrepareDownload;

  /// Removes an unapproved browser request that disconnected or expired.
  const factory RsServerEvent.webPrepareDownloadAborted({
    required String sessionId,
  }) = RsServerEvent_WebPrepareDownloadAborted;

  /// A web client downloads an offered file via `GET /api/localsend/v2/download`.
  ///
  /// Must be answered with [RsHttpServer::respond_file_download].
  const factory RsServerEvent.webFileDownload({
    required String requestId,
    required String sessionId,
    required String fileId,
    required FileDto file,
  }) = RsServerEvent_WebFileDownload;

  /// Another application instance requested the running application to show itself
  /// via `POST /api/localsend/v2/show`.
  const factory RsServerEvent.show_({
    /// Command-line arguments forwarded by the other application instance.
    required List<String> args,
  }) = RsServerEvent_Show;

  /// The listening socket failed permanently, e.g. because the OS
  /// invalidated it while the application was suspended (iOS reclaims the
  /// sockets of suspended apps). The server has stopped itself; the
  /// application must restart it to become reachable again.
  const factory RsServerEvent.listenerFailed({
    /// Description of the failure.
    required String error,
  }) = RsServerEvent_ListenerFailed;
}

enum SessionEndReasonV2 {
  finished,
  cancelled,
  expired,
}

class TlsConfig {
  final String cert;
  final String privateKey;

  const TlsConfig({
    required this.cert,
    required this.privateKey,
  });

  @override
  int get hashCode => cert.hashCode ^ privateKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is TlsConfig && runtimeType == other.runtimeType && cert == other.cert && privateKey == other.privateKey;
}

class WebI18n {
  final String waiting;
  final String enterPin;
  final String invalidPin;
  final String tooManyAttempts;
  final String rejected;
  final String uploadRejected;
  final String busy;
  final String files;
  final String fileName;
  final String size;
  final String dropHint;
  final String? preview;
  final String? closePreview;
  final String? downloadOriginal;
  final String? previewLoading;
  final String? previewError;
  final String? previewUnsupported;
  final Map<String, String>? textPreview;

  const WebI18n({
    required this.waiting,
    required this.enterPin,
    required this.invalidPin,
    required this.tooManyAttempts,
    required this.rejected,
    required this.uploadRejected,
    required this.busy,
    required this.files,
    required this.fileName,
    required this.size,
    required this.dropHint,
    this.preview,
    this.closePreview,
    this.downloadOriginal,
    this.previewLoading,
    this.previewError,
    this.previewUnsupported,
    this.textPreview,
  });

  @override
  int get hashCode =>
      waiting.hashCode ^
      enterPin.hashCode ^
      invalidPin.hashCode ^
      tooManyAttempts.hashCode ^
      rejected.hashCode ^
      uploadRejected.hashCode ^
      busy.hashCode ^
      files.hashCode ^
      fileName.hashCode ^
      size.hashCode ^
      dropHint.hashCode ^
      preview.hashCode ^
      closePreview.hashCode ^
      downloadOriginal.hashCode ^
      previewLoading.hashCode ^
      previewError.hashCode ^
      previewUnsupported.hashCode ^
      textPreview.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebI18n &&
          runtimeType == other.runtimeType &&
          waiting == other.waiting &&
          enterPin == other.enterPin &&
          invalidPin == other.invalidPin &&
          tooManyAttempts == other.tooManyAttempts &&
          rejected == other.rejected &&
          uploadRejected == other.uploadRejected &&
          busy == other.busy &&
          files == other.files &&
          fileName == other.fileName &&
          size == other.size &&
          dropHint == other.dropHint &&
          preview == other.preview &&
          closePreview == other.closePreview &&
          downloadOriginal == other.downloadOriginal &&
          previewLoading == other.previewLoading &&
          previewError == other.previewError &&
          previewUnsupported == other.previewUnsupported &&
          textPreview == other.textPreview;
}

@freezed
sealed class WebMode with _$WebMode {
  const WebMode._();

  /// No web share active: `/` serves the 403 page and client certificates
  /// are mandatory under TLS, so the 403 page is effectively only reachable
  /// when encryption is off.
  const factory WebMode.disabled() = WebMode_Disabled;

  /// Web download: the download page and the download API, offering files for
  /// download by web browsers.
  ///
  /// Web download can be enabled independently of the v2 protocol endpoints.
  const factory WebMode.download({
    /// The metadata of the files offered for download, mapped by file ID.
    /// The content is requested per download via [RsServerEvent::WebFileDownload].
    required Map<String, FileDto> files,

    /// Optional PIN that web clients must provide via the `pin` query parameter.
    String? pin,
  }) = WebMode_Download;

  /// The upload page: web browsers upload files via the v2
  /// `prepare-upload`/`upload` endpoints.
  const factory WebMode.upload() = WebMode_Upload;

  /// Persistent bidirectional browser workspace.
  const factory WebMode.duplex({
    required Map<String, FileDto> files,
    String? pin,
    required bool allowUpload,
  }) = WebMode_Duplex;
}

class WebPages {
  final String? downloadHtml;
  final String? uploadHtml;
  final String? error403Html;

  const WebPages({
    this.downloadHtml,
    this.uploadHtml,
    this.error403Html,
  });

  @override
  int get hashCode => downloadHtml.hashCode ^ uploadHtml.hashCode ^ error403Html.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebPages &&
          runtimeType == other.runtimeType &&
          downloadHtml == other.downloadHtml &&
          uploadHtml == other.uploadHtml &&
          error403Html == other.error403Html;
}

/// Configuration for the pages served to browsers. Always part of the server
/// configuration: even with web share disabled ([WebMode::Disabled]), the
/// server serves the 403 page at `/`.
class WebParams {
  /// What is served at `/` and which browser-facing API is active.
  final WebMode mode;

  /// Translations for the web pages, served via `/i18n.json`.
  final WebI18n i18N;

  /// Custom HTML pages replacing the embedded web pages.
  /// Pages left `null` are served from the assets embedded at compile time.
  final WebPages pages;

  const WebParams({
    required this.mode,
    required this.i18N,
    required this.pages,
  });

  @override
  int get hashCode => mode.hashCode ^ i18N.hashCode ^ pages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebParams && runtimeType == other.runtimeType && mode == other.mode && i18N == other.i18N && pages == other.pages;
}
